"""Invitation model for controlling private registrations."""

from __future__ import annotations

import enum
from datetime import datetime
from typing import Any, Optional, cast
from uuid import UUID

from sqlalchemy import (
    Column,
    DateTime,
    Enum,
    ForeignKey,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import relationship

from app.db.models.base import SCHEMA_NAME, Base, SoftDeleteMixin, TimestampMixin


class InvitationStatus(str, enum.Enum):
    """Enumeration of invitation states."""

    PENDING = "pending"
    REGISTERED = "registered"
    REVOKED = "revoked"
    EXPIRED = "expired"


class Invitation(Base, TimestampMixin, SoftDeleteMixin):
    """Invitation codes generated by admins to gate registrations."""

    __tablename__ = "invitations"
    __table_args__ = (
        UniqueConstraint(
            "creator_user_id",
            "target_email",
            name="uq_invitations_creator_email",
        ),
        {"schema": SCHEMA_NAME},
    )

    code = Column(
        String(64),
        nullable=False,
        unique=True,
        comment="Invitation code token",
    )
    creator_user_id = Column(
        PG_UUID(as_uuid=True),
        ForeignKey(f"{SCHEMA_NAME}.users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="User who generated the invitation",
    )
    target_email = Column(
        String(255),
        nullable=False,
        index=True,
        comment="Email address the invitation is bound to (lowercase)",
    )
    status: Any = Column(
        Enum(
            InvitationStatus,
            name="invitation_status",
            schema=SCHEMA_NAME,
        ),
        nullable=False,
        default=InvitationStatus.PENDING,
        comment="Current invitation status",
    )
    target_user_id = Column(
        PG_UUID(as_uuid=True),
        ForeignKey(f"{SCHEMA_NAME}.users.id", ondelete="SET NULL"),
        nullable=True,
        comment="User who registered with this invitation",
    )
    registered_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp when the invite was used for registration",
    )
    revoked_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp when the invite was revoked",
    )
    expires_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="Optional expiration timestamp",
    )
    memo = Column(
        Text,
        nullable=True,
        comment="Operational notes about this invitation",
    )

    creator = relationship(
        "User",
        foreign_keys=[creator_user_id],
        lazy="joined",
    )
    target_user = relationship(
        "User",
        foreign_keys=[target_user_id],
        lazy="joined",
    )

    def mark_registered(self, user_id: UUID, *, reason: Optional[str] = None) -> None:
        """Mark invitation as successfully registered by a user."""

        setattr(self, "status", InvitationStatus.REGISTERED)
        setattr(self, "target_user_id", user_id)
        setattr(self, "registered_at", func.now())
        if reason:
            memo = cast(str | None, self.memo)
            setattr(self, "memo", f"{memo}\n{reason}" if memo else reason)

    def mark_revoked(self, *, reason: Optional[str] = None) -> None:
        """Soft delete and revoke the invitation."""

        setattr(self, "status", InvitationStatus.REVOKED)
        setattr(self, "revoked_at", func.now())
        if reason:
            memo = cast(str | None, self.memo)
            setattr(self, "memo", f"{memo}\n{reason}" if memo else reason)
        self.soft_delete()

    def mark_expired(self, timestamp: Optional[datetime] = None) -> None:
        """Mark invitation as expired without deleting it."""

        setattr(self, "status", InvitationStatus.EXPIRED)
        setattr(self, "revoked_at", timestamp or func.now())
