"""add session token totals

Revision ID: 1d17a2498747
Revises: 3e5c3b356025
Create Date: 2025-10-13 13:53:53.187446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d17a2498747'
down_revision = '3e5c3b356025'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_sessions', sa.Column('prompt_tokens_total', sa.Integer(), nullable=False,server_default='0', comment='Accumulated prompt tokens for the session'), schema='common_compass_schema')
    op.add_column('agent_sessions', sa.Column('completion_tokens_total', sa.Integer(), nullable=False, server_default='0',comment='Accumulated completion tokens for the session'), schema='common_compass_schema')
    op.add_column('agent_sessions', sa.Column('total_tokens_total', sa.Integer(), nullable=False, server_default='0',comment='Accumulated total tokens for the session'), schema='common_compass_schema')
    op.add_column('agent_sessions', sa.Column('cost_usd_total', sa.Numeric(precision=10, scale=6), nullable=False, server_default='0',comment='Accumulated USD cost for the session'), schema='common_compass_schema')
    # ### end Alembic commands ###


    op.execute(
        """
        UPDATE {schema}.agent_sessions AS s
        SET
            prompt_tokens_total = COALESCE(agg.prompt_tokens_total, 0),
            completion_tokens_total = COALESCE(agg.completion_tokens_total, 0),
            total_tokens_total = COALESCE(agg.total_tokens_total, 0),
            cost_usd_total = COALESCE(agg.cost_usd_total, 0)
        FROM (
            SELECT
                session_id,
                SUM(COALESCE(prompt_tokens, 0)) AS prompt_tokens_total,
                SUM(COALESCE(completion_tokens, 0)) AS completion_tokens_total,
                SUM(COALESCE(total_tokens, 0)) AS total_tokens_total,
                SUM(COALESCE(cost_usd, 0)) AS cost_usd_total
            FROM {schema}.agent_messages
            WHERE session_id IS NOT NULL
            GROUP BY session_id
        ) AS agg
        WHERE s.id = agg.session_id
        """.format(schema='common_compass_schema')
    )

    op.alter_column(
        'agent_sessions',
        'prompt_tokens_total',
        server_default=None,
        schema='common_compass_schema',
    )
    op.alter_column(
        'agent_sessions',
        'completion_tokens_total',
        server_default=None,
        schema='common_compass_schema',
    )
    op.alter_column(
        'agent_sessions',
        'total_tokens_total',
        server_default=None,
        schema='common_compass_schema',
    )
    op.alter_column(
        'agent_sessions',
        'cost_usd_total',
        server_default=None,
        schema='common_compass_schema',
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_sessions', 'cost_usd_total', schema='common_compass_schema')
    op.drop_column('agent_sessions', 'total_tokens_total', schema='common_compass_schema')
    op.drop_column('agent_sessions', 'completion_tokens_total', schema='common_compass_schema')
    op.drop_column('agent_sessions', 'prompt_tokens_total', schema='common_compass_schema')
    # ### end Alembic commands ###
