"""expand_agent_notifications

Revision ID: 6838112514e9
Revises: d14d01619ac2
Create Date: 2025-10-29 22:41:34.533511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6838112514e9'
down_revision = 'd14d01619ac2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_message_receipts',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=False, comment='When the notification was enqueued for the user'),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the user read the message'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.ForeignKeyConstraint(['message_id'], ['common_compass_schema.agent_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', deferrable=True, initially='DEFERRED', name='uq_agent_message_receipts_message_user'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_agent_message_receipts_message_id'), 'agent_message_receipts', ['message_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_agent_message_receipts_user_id'), 'agent_message_receipts', ['user_id'], unique=False, schema='common_compass_schema')
    op.add_column('agent_messages', sa.Column('severity', sa.String(length=16), server_default='info', nullable=False, comment='Notification severity indicator for system messages'), schema='common_compass_schema')
    op.alter_column('agent_messages', 'sender',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=16),
               comment='Source of the message: user/agent/system/automation',
               existing_nullable=False,
               schema='common_compass_schema')
    op.add_column('agent_sessions', sa.Column('session_type', sa.String(length=32), server_default='chat', nullable=False, comment='Session classification: chat/system/scheduled'), schema='common_compass_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_sessions', 'session_type', schema='common_compass_schema')
    op.alter_column('agent_messages', 'sender',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Source of the message: user/agent/system/automation',
               existing_nullable=False,
               schema='common_compass_schema')
    op.drop_column('agent_messages', 'severity', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_agent_message_receipts_user_id'), table_name='agent_message_receipts', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_agent_message_receipts_message_id'), table_name='agent_message_receipts', schema='common_compass_schema')
    op.drop_table('agent_message_receipts', schema='common_compass_schema')
    # ### end Alembic commands ###
