"""add_audit_columns_finance_entries

Revision ID: 9e051fca31d6
Revises: f1d9e4d2add5
Create Date: 2025-10-17 15:31:16.870559

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9e051fca31d6'
down_revision = 'f1d9e4d2add5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashflow_snapshot_entries', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'), schema='common_compass_schema')
    op.add_column('cashflow_snapshot_entries', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'), schema='common_compass_schema')
    op.add_column('cashflow_snapshot_entries', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'), schema='common_compass_schema')
    op.alter_column('cashflow_snapshot_entries', 'id',
               existing_type=sa.UUID(),
               comment='Primary key (UUID v4)',
               existing_nullable=False,
               schema='common_compass_schema')
    op.add_column('finance_snapshot_entries', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'), schema='common_compass_schema')
    op.add_column('finance_snapshot_entries', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'), schema='common_compass_schema')
    op.add_column('finance_snapshot_entries', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'), schema='common_compass_schema')
    op.alter_column('finance_snapshot_entries', 'id',
               existing_type=sa.UUID(),
               comment='Primary key (UUID v4)',
               existing_nullable=False,
               schema='common_compass_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finance_snapshot_entries', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key (UUID v4)',
               existing_nullable=False,
               schema='common_compass_schema')
    op.drop_column('finance_snapshot_entries', 'deleted_at', schema='common_compass_schema')
    op.drop_column('finance_snapshot_entries', 'updated_at', schema='common_compass_schema')
    op.drop_column('finance_snapshot_entries', 'created_at', schema='common_compass_schema')
    op.alter_column('cashflow_snapshot_entries', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key (UUID v4)',
               existing_nullable=False,
               schema='common_compass_schema')
    op.drop_column('cashflow_snapshot_entries', 'deleted_at', schema='common_compass_schema')
    op.drop_column('cashflow_snapshot_entries', 'updated_at', schema='common_compass_schema')
    op.drop_column('cashflow_snapshot_entries', 'created_at', schema='common_compass_schema')
    # ### end Alembic commands ###
