"""add_agent_message_metadata

Revision ID: 969950a8b368
Revises: 1d17a2498747
Create Date: 2025-10-13 18:29:29.778483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '969950a8b368'
down_revision = '1d17a2498747'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_messages', sa.Column('message_type', sa.String(length=32), nullable=False,server_default='chat', comment='Message classification (chat/tool/system/etc.)'), schema='common_compass_schema')
    op.add_column('agent_messages', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured metadata for the message (tool info, etc.)'), schema='common_compass_schema')
    op.execute(
        sa.text(
            "UPDATE {schema}.{table} SET message_type = 'chat' WHERE message_type IS NULL".format(
                schema='common_compass_schema',
                table='agent_messages',
            )
        )
    )

    op.alter_column(
        'agent_messages',
        'message_type',
        server_default=None,
        schema='common_compass_schema',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_messages', 'metadata', schema='common_compass_schema')
    op.drop_column('agent_messages', 'message_type', schema='common_compass_schema')
    # ### end Alembic commands ###
