"""add trading plan

Revision ID: 814f7cb4c87b
Revises: 6056acf817f6
Create Date: 2025-11-17 20:08:46.340257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814f7cb4c87b'
down_revision = '6056acf817f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('base_asset', sa.String(length=32), nullable=False),
    sa.Column('quote_asset', sa.String(length=32), nullable=False),
    sa.Column('rate', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_exchange_rates_captured_at'), 'exchange_rates', ['captured_at'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_exchange_rates_user_id'), 'exchange_rates', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_index('ix_exchange_rates_pair_time', 'exchange_rates', ['base_asset', 'quote_asset', 'captured_at'], unique=False, schema='common_compass_schema')
    op.create_index('ix_exchange_rates_source', 'exchange_rates', ['source'], unique=False, schema='common_compass_schema')
    op.create_table('trading_plans',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_roi', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.CheckConstraint("status IN ('draft', 'active', 'archived')", name='ck_trading_plans_valid_status'),
    sa.CheckConstraint('period_end IS NULL OR period_start IS NULL OR period_end >= period_start', name='ck_trading_plans_period_range'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_trading_plans_name'), 'trading_plans', ['name'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_trading_plans_user_id'), 'trading_plans', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_index('ix_trading_plans_user_period', 'trading_plans', ['user_id', 'period_start', 'period_end'], unique=False, schema='common_compass_schema')
    op.create_index('ix_trading_plans_user_status', 'trading_plans', ['user_id', 'status'], unique=False, schema='common_compass_schema')
    op.create_table('trading_instruments',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('base_asset', sa.String(length=32), nullable=False),
    sa.Column('quote_asset', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=64), nullable=True),
    sa.Column('strategy_tag', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.ForeignKeyConstraint(['plan_id'], ['common_compass_schema.trading_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_trading_instruments_plan_id'), 'trading_instruments', ['plan_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_trading_instruments_user_id'), 'trading_instruments', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_index('ix_trading_instruments_plan_symbol', 'trading_instruments', ['plan_id', 'symbol'], unique=False, schema='common_compass_schema')
    op.create_index('ix_trading_instruments_user_plan', 'trading_instruments', ['user_id', 'plan_id'], unique=False, schema='common_compass_schema')
    op.create_index('uq_trading_instruments_plan_symbol_active', 'trading_instruments', ['plan_id', 'symbol'], unique=True, schema='common_compass_schema', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('trading_entries',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('trade_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('base_delta', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('quote_delta', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('price', sa.Numeric(precision=30, scale=12), nullable=True),
    sa.Column('fee_asset', sa.String(length=32), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=30, scale=12), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.CheckConstraint("direction IN ('buy', 'sell', 'transfer')", name='ck_trading_entries_direction'),
    sa.CheckConstraint("source IN ('manual', 'import')", name='ck_trading_entries_source'),
    sa.ForeignKeyConstraint(['instrument_id'], ['common_compass_schema.trading_instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['common_compass_schema.trading_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_trading_entries_instrument_id'), 'trading_entries', ['instrument_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_trading_entries_plan_id'), 'trading_entries', ['plan_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_trading_entries_user_id'), 'trading_entries', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_index('ix_trading_entries_instrument_time', 'trading_entries', ['instrument_id', 'trade_time'], unique=False, schema='common_compass_schema')
    op.create_index('ix_trading_entries_user_plan_time', 'trading_entries', ['user_id', 'plan_id', 'trade_time'], unique=False, schema='common_compass_schema')
    op.create_table('trading_instrument_metrics',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('total_base_in', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('total_base_out', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('net_position', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=30, scale=12), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.ForeignKeyConstraint(['instrument_id'], ['common_compass_schema.trading_instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['common_compass_schema.trading_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'instrument_id', name='uq_trading_instrument_metrics_fk'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_trading_instrument_metrics_user_id'), 'trading_instrument_metrics', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_index('ix_trading_instrument_metrics_plan', 'trading_instrument_metrics', ['plan_id', 'instrument_id'], unique=False, schema='common_compass_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trading_instrument_metrics_plan', table_name='trading_instrument_metrics', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_trading_instrument_metrics_user_id'), table_name='trading_instrument_metrics', schema='common_compass_schema')
    op.drop_table('trading_instrument_metrics', schema='common_compass_schema')
    op.drop_index('ix_trading_entries_user_plan_time', table_name='trading_entries', schema='common_compass_schema')
    op.drop_index('ix_trading_entries_instrument_time', table_name='trading_entries', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_trading_entries_user_id'), table_name='trading_entries', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_trading_entries_plan_id'), table_name='trading_entries', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_trading_entries_instrument_id'), table_name='trading_entries', schema='common_compass_schema')
    op.drop_table('trading_entries', schema='common_compass_schema')
    op.drop_index('uq_trading_instruments_plan_symbol_active', table_name='trading_instruments', schema='common_compass_schema', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_trading_instruments_user_plan', table_name='trading_instruments', schema='common_compass_schema')
    op.drop_index('ix_trading_instruments_plan_symbol', table_name='trading_instruments', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_trading_instruments_user_id'), table_name='trading_instruments', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_trading_instruments_plan_id'), table_name='trading_instruments', schema='common_compass_schema')
    op.drop_table('trading_instruments', schema='common_compass_schema')
    op.drop_index('ix_trading_plans_user_status', table_name='trading_plans', schema='common_compass_schema')
    op.drop_index('ix_trading_plans_user_period', table_name='trading_plans', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_trading_plans_user_id'), table_name='trading_plans', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_trading_plans_name'), table_name='trading_plans', schema='common_compass_schema')
    op.drop_table('trading_plans', schema='common_compass_schema')
    op.drop_index('ix_exchange_rates_source', table_name='exchange_rates', schema='common_compass_schema')
    op.drop_index('ix_exchange_rates_pair_time', table_name='exchange_rates', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_exchange_rates_user_id'), table_name='exchange_rates', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_exchange_rates_captured_at'), table_name='exchange_rates', schema='common_compass_schema')
    op.drop_table('exchange_rates', schema='common_compass_schema')
    # ### end Alembic commands ###
