"""add aggregated dimension stats

Revision ID: 3e5c3b356025
Revises: 46d22bc1e2fe
Create Date: 2025-10-10 13:18:44.036899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5c3b356025'
down_revision = '46d22bc1e2fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregated_dimension_stats',
    sa.Column('granularity', sa.Enum('day', 'week', 'month', 'year', name='aggregationgranularity', schema='common_compass_schema'), nullable=False, comment='Aggregation granularity (day/week/month/year)'),
    sa.Column('period_start', sa.Date(), nullable=False, comment='Inclusive start date for the aggregation bucket'),
    sa.Column('period_end', sa.Date(), nullable=False, comment='Inclusive end date for the aggregation bucket'),
    sa.Column('timezone', sa.String(length=64), nullable=False, comment='Timezone identifier used for this aggregation'),
    sa.Column('calendar_system', sa.String(length=32), nullable=False, comment='Calendar system used when deriving the bucket'),
    sa.Column('first_day_of_week', sa.Integer(), server_default='0', nullable=False, comment='First day of week (1=Monday...7=Sunday) when granularity is week; 0 for non-week'),
    sa.Column('dimension_id', sa.UUID(), nullable=False, comment='Referenced dimension id'),
    sa.Column('minutes', sa.Integer(), nullable=False, comment='Total minutes aggregated for the bucket'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['dimension_id'], ['common_compass_schema.dimensions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'granularity', 'timezone', 'calendar_system', 'first_day_of_week', 'period_start', 'period_end', 'dimension_id', name='uq_aggregated_dim_stats_user_period_dim'),
    schema='common_compass_schema'
    )
    op.create_index('ix_agg_dim_user_granularity_period', 'aggregated_dimension_stats', ['user_id', 'granularity', 'timezone', 'period_start'], unique=False, schema='common_compass_schema')
    op.create_index('ix_agg_dim_user_period_range', 'aggregated_dimension_stats', ['user_id', 'timezone', 'period_start', 'period_end'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_aggregated_dimension_stats_id'), 'aggregated_dimension_stats', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_aggregated_dimension_stats_user_id'), 'aggregated_dimension_stats', ['user_id'], unique=False, schema='common_compass_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_common_compass_schema_aggregated_dimension_stats_user_id'), table_name='aggregated_dimension_stats', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_aggregated_dimension_stats_id'), table_name='aggregated_dimension_stats', schema='common_compass_schema')
    op.drop_index('ix_agg_dim_user_period_range', table_name='aggregated_dimension_stats', schema='common_compass_schema')
    op.drop_index('ix_agg_dim_user_granularity_period', table_name='aggregated_dimension_stats', schema='common_compass_schema')
    op.drop_table('aggregated_dimension_stats', schema='common_compass_schema')
    # ### end Alembic commands ###
