"""add ix_tasks_user_cycle_type_start index

Revision ID: 011a19ab762d
Revises: cdbc065ed2b2
Create Date: 2025-10-26 12:25:14.438182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011a19ab762d'
down_revision = 'cdbc065ed2b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tasks_user_cycle_type_start', 'tasks', ['user_id', 'planning_cycle_type', 'planning_cycle_start_date'], unique=False, schema='common_compass_schema', postgresql_where=sa.text('planning_cycle_start_date IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_user_cycle_type_start', table_name='tasks', schema='common_compass_schema', postgresql_where=sa.text('planning_cycle_start_date IS NOT NULL'))
    # ### end Alembic commands ###
