"""Simplify habit action status

Revision ID: 6056acf817f6
Revises: 019c95caa9b1
Create Date: 2025-11-15 20:31:25.815814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6056acf817f6'
down_revision = '019c95caa9b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habit_actions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment="Action status: 'pending', 'done', 'skip', 'miss'",
               existing_comment="Action status: 'inbox', 'todo', 'doing', 'done', 'failed', 'pass'",
               existing_nullable=False,
               schema='common_compass_schema')
    # Convert existing habit action statuses
    conn = op.get_bind()

    # Drop the old check constraint and add new one
    conn.execute(sa.text("""
        ALTER TABLE common_compass_schema.habit_actions
        DROP CONSTRAINT IF EXISTS valid_action_status
    """))

    # Update habit actions with new status values
    conn.execute(sa.text("""
        UPDATE common_compass_schema.habit_actions
        SET status = CASE
            WHEN status IN ('inbox', 'todo') THEN 'pending'
            WHEN status = 'doing' THEN 'done'
            WHEN status = 'failed' THEN 'miss'
            WHEN status = 'pass' THEN 'skip'
            ELSE status
        END
        WHERE status IN ('inbox', 'todo', 'doing', 'failed', 'pass')
    """))



    conn.execute(sa.text("""
        ALTER TABLE common_compass_schema.habit_actions
        ADD CONSTRAINT valid_action_status
        CHECK (status IN ('pending', 'done', 'skip', 'miss'))
    """))


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habit_actions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment="Action status: 'inbox', 'todo', 'doing', 'done', 'failed', 'pass'",
               existing_comment="Action status: 'pending', 'done', 'skip', 'miss'",
               existing_nullable=False,
               schema='common_compass_schema')

    # Convert back to old statuses
    conn = op.get_bind()

    # Drop new constraint and restore old one
    conn.execute(sa.text("""
        ALTER TABLE common_compass_schema.habit_actions
        DROP CONSTRAINT IF EXISTS valid_action_status
    """))

    # Note: This is a lossy conversion since we're merging states
    conn.execute(sa.text("""
        UPDATE common_compass_schema.habit_actions
        SET status = CASE
            WHEN status = 'pending' THEN 'todo'  -- Default to todo for pending
            WHEN status = 'done' THEN 'done'     -- Keep done as is
            WHEN status = 'skip' THEN 'pass'     -- Convert skip back to pass
            WHEN status = 'miss' THEN 'failed'   -- Convert miss back to failed
            ELSE status
        END
        WHERE status IN ('pending', 'done', 'skip', 'miss')
    """))


    conn.execute(sa.text("""
        ALTER TABLE common_compass_schema.habit_actions
        ADD CONSTRAINT valid_action_status
        CHECK (status IN ('inbox', 'todo', 'doing', 'done', 'failed', 'pass'))
    """))

    # ### end Alembic commands ###
