"""add user llm credentials table

Revision ID: 167eb8d8d0f6
Revises: eda2163416bf
Create Date: 2025-11-19 21:57:47.660348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167eb8d8d0f6'
down_revision = 'eda2163416bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_llm_credentials',
    sa.Column('provider', sa.String(length=64), nullable=False, comment='Provider key (e.g., openai, azure-openai, custom)'),
    sa.Column('display_name', sa.String(length=120), nullable=True, comment='User-friendly label for the credential'),
    sa.Column('api_base', sa.String(length=255), nullable=True, comment='Optional override for provider base URL'),
    sa.Column('model_override', sa.String(length=255), nullable=True, comment='Preferred model when using this credential'),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False, comment='Encrypted API token (Fernet)'),
    sa.Column('token_last4', sa.String(length=12), nullable=True, comment='Last four characters of the plain token for display'),
    sa.Column('encryption_version', sa.Integer(), server_default='1', nullable=False, comment='Secret encryption version'),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False, comment='Whether this credential is the default for the user'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last successful usage'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'display_name', name='uq_user_llm_credentials_user_label'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_user_llm_credentials_user_id'), 'user_llm_credentials', ['user_id'], unique=False, schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_agent_audit_log_agent_name'), table_name='agent_audit_log', schema='common_compass_schema')
    op.add_column('user_daily_llm_usage', sa.Column('system_tokens_total', sa.Integer(), server_default='0', nullable=False, comment='Tokens billed to system-provided credentials'), schema='common_compass_schema')
    op.add_column('user_daily_llm_usage', sa.Column('system_request_count', sa.Integer(), server_default='0', nullable=False, comment='Request count billed to system-provided credentials'), schema='common_compass_schema')
    op.add_column('user_daily_llm_usage', sa.Column('user_tokens_total', sa.Integer(), server_default='0', nullable=False, comment='Tokens billed to BYOT credentials'), schema='common_compass_schema')
    op.add_column('user_daily_llm_usage', sa.Column('user_request_count', sa.Integer(), server_default='0', nullable=False, comment='Request count billed to BYOT credentials'), schema='common_compass_schema')
    # ### end Alembic commands ###

    op.execute(
        sa.text(
            f"""
            UPDATE common_compass_schema.user_daily_llm_usage
            SET system_tokens_total = tokens_total,
                system_request_count = request_count,
                user_tokens_total = 0,
                user_request_count = 0
            """
        )
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_daily_llm_usage', 'user_request_count', schema='common_compass_schema')
    op.drop_column('user_daily_llm_usage', 'user_tokens_total', schema='common_compass_schema')
    op.drop_column('user_daily_llm_usage', 'system_request_count', schema='common_compass_schema')
    op.drop_column('user_daily_llm_usage', 'system_tokens_total', schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_agent_audit_log_agent_name'), 'agent_audit_log', ['agent_name'], unique=False, schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_user_llm_credentials_user_id'), table_name='user_llm_credentials', schema='common_compass_schema')
    op.drop_table('user_llm_credentials', schema='common_compass_schema')
    # ### end Alembic commands ###
