"""add available_at

Revision ID: d14d01619ac2
Revises: 011a19ab762d
Create Date: 2025-10-29 21:35:00.716634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14d01619ac2'
down_revision = '011a19ab762d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_recalc_jobs', sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Earliest time when the job becomes eligible for processing'), schema='common_compass_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_recalc_jobs', 'available_at', schema='common_compass_schema')
    # ### end Alembic commands ###
