"""add vision exp rate

Revision ID: a216ede0bc21
Revises: b8b6306f4dc4
Create Date: 2025-10-18 20:54:22.919235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a216ede0bc21'
down_revision = 'b8b6306f4dc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visions', sa.Column('experience_rate_per_hour', sa.Integer(), nullable=True, comment='Optional override: experience points gained per hour of effort'), schema='common_compass_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visions', 'experience_rate_per_hour', schema='common_compass_schema')
    # ### end Alembic commands ###
