"""Add user activity table and login state columns

Revision ID: 7fa8521f1113
Revises: de6d75d7f88a
Create Date: 2025-11-18 15:40:06.138142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fa8521f1113'
down_revision = 'de6d75d7f88a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity',
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Associated user if available'),
    sa.Column('event_type', sa.String(length=64), nullable=False, comment='Classification of the recorded activity'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Outcome descriptor (e.g. success/failed/blocked)'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Flexible metadata payload for the event'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_user_activity_event_type'), 'user_activity', ['event_type'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_user_activity_user_id'), 'user_activity', ['user_id'], unique=False, schema='common_compass_schema')
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False, comment='Consecutive failed login attempts since last success'), schema='common_compass_schema')
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='Account temporarily locked until this timestamp'), schema='common_compass_schema')
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the most recent successful login'), schema='common_compass_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at', schema='common_compass_schema')
    op.drop_column('users', 'locked_until', schema='common_compass_schema')
    op.drop_column('users', 'failed_login_attempts', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_user_activity_user_id'), table_name='user_activity', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_user_activity_event_type'), table_name='user_activity', schema='common_compass_schema')
    op.drop_table('user_activity', schema='common_compass_schema')
    # ### end Alembic commands ###
