"""add agent audit log table

Revision ID: eda2163416bf
Revises: 7fa8521f1113
Create Date: 2025-11-19 17:00:19.361247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eda2163416bf'
down_revision = '7fa8521f1113'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_audit_log',
    sa.Column('run_id', sa.UUID(), nullable=False, comment='Correlates records belonging to the same tool execution'),
    sa.Column('trigger_user_id', sa.UUID(), nullable=False, comment='User on whose behalf the agent acted'),
    sa.Column('session_id', sa.UUID(), nullable=True, comment='Agent session context if available'),
    sa.Column('message_id', sa.UUID(), nullable=True, comment='Agent message that triggered the tool call'),
    sa.Column('agent_name', sa.String(length=64), nullable=False, comment='Agent profile name'),
    sa.Column('tool_name', sa.String(length=128), nullable=False, comment='Executed tool'),
    sa.Column('tool_call_id', sa.String(length=128), nullable=True, comment='Upstream LLM tool_call identifier if provided'),
    sa.Column('operation', sa.String(length=128), nullable=True, comment='Business-level operation descriptor reported by the tool'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Execution outcome (finished/failed/partial)'),
    sa.Column('error', sa.Text(), nullable=True, comment='Error message when execution failed'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='Execution duration reported by the tool'),
    sa.Column('target_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured summary of impacted entities/types'),
    sa.Column('before_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Redacted snapshot or diff before execution'),
    sa.Column('after_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Redacted snapshot or diff after execution'),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional metadata payload (arguments, tool-specific info)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['session_id'], ['common_compass_schema.agent_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trigger_user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_agent_audit_log_agent_name'), 'agent_audit_log', ['agent_name'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_agent_audit_log_message_id'), 'agent_audit_log', ['message_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_agent_audit_log_operation'), 'agent_audit_log', ['operation'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_agent_audit_log_run_id'), 'agent_audit_log', ['run_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_agent_audit_log_session_id'), 'agent_audit_log', ['session_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_agent_audit_log_tool_name'), 'agent_audit_log', ['tool_name'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_agent_audit_log_trigger_user_id'), 'agent_audit_log', ['trigger_user_id'], unique=False, schema='common_compass_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_common_compass_schema_agent_audit_log_trigger_user_id'), table_name='agent_audit_log', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_agent_audit_log_tool_name'), table_name='agent_audit_log', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_agent_audit_log_session_id'), table_name='agent_audit_log', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_agent_audit_log_run_id'), table_name='agent_audit_log', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_agent_audit_log_operation'), table_name='agent_audit_log', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_agent_audit_log_message_id'), table_name='agent_audit_log', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_agent_audit_log_agent_name'), table_name='agent_audit_log', schema='common_compass_schema')
    op.drop_table('agent_audit_log', schema='common_compass_schema')
    # ### end Alembic commands ###
