"""add work_recalc_jobs

Revision ID: cdbc065ed2b2
Revises: c8d1e9c3c2fb
Create Date: 2025-10-25 21:32:48.308539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbc065ed2b2'
down_revision = 'c8d1e9c3c2fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_recalc_jobs',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner of the job'),
    sa.Column('entity_type', sa.Enum('task', 'vision', name='work_recalc_entity_type', schema='common_compass_schema'), nullable=False, comment='Entity type that requires recomputation'),
    sa.Column('entity_id', sa.UUID(), nullable=False, comment='Primary key of the entity that should be recalculated'),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='work_recalc_status', schema='common_compass_schema'), server_default='pending', nullable=False, comment='Processing status for the job'),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False, comment='Higher value processed first'),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False, comment='Number of retry attempts'),
    sa.Column('reason', sa.String(length=255), nullable=True, comment='Optional reason / debug info for scheduling'),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last processing attempt'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Job creation timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_work_recalc_jobs_entity'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_work_recalc_jobs_user_id'), 'work_recalc_jobs', ['user_id'], unique=False, schema='common_compass_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_common_compass_schema_work_recalc_jobs_user_id'), table_name='work_recalc_jobs', schema='common_compass_schema')
    op.drop_table('work_recalc_jobs', schema='common_compass_schema')
    # ### end Alembic commands ###
