"""add invitations table

Revision ID: 66f91eb2388d
Revises: 7f2d4c6b8a90
Create Date: 2025-11-06 15:08:37.339238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f91eb2388d'
down_revision = '7f2d4c6b8a90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('code', sa.String(length=64), nullable=False, comment='Invitation code token'),
    sa.Column('creator_user_id', sa.UUID(), nullable=False, comment='User who generated the invitation'),
    sa.Column('target_email', sa.String(length=255), nullable=False, comment='Email address the invitation is bound to (lowercase)'),
    sa.Column('status', sa.Enum('PENDING', 'REGISTERED', 'REVOKED', 'EXPIRED', name='invitation_status', schema='common_compass_schema'), nullable=False, comment='Current invitation status'),
    sa.Column('target_user_id', sa.UUID(), nullable=True, comment='User who registered with this invitation'),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the invite was used for registration'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the invite was revoked'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Optional expiration timestamp'),
    sa.Column('memo', sa.Text(), nullable=True, comment='Operational notes about this invitation'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.ForeignKeyConstraint(['creator_user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['common_compass_schema.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('creator_user_id', 'target_email', name='uq_invitations_creator_email'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_invitations_creator_user_id'), 'invitations', ['creator_user_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_invitations_target_email'), 'invitations', ['target_email'], unique=False, schema='common_compass_schema')
    op.alter_column('cashflow_billing_entries', 'posted_month',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='First day of natural month',
               existing_nullable=False,
               schema='common_compass_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cashflow_billing_entries', 'posted_month',
               existing_type=sa.DATE(),
               comment='First day of natural month',
               existing_nullable=False,
               schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_invitations_target_email'), table_name='invitations', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_invitations_creator_user_id'), table_name='invitations', schema='common_compass_schema')
    op.drop_table('invitations', schema='common_compass_schema')
    # ### end Alembic commands ###
