"""Init

Revision ID: 68e3e7021941
Revises:
Create Date: 2025-10-01 15:48:32.455914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68e3e7021941'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address (unique)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='User display name'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hashed password using bcrypt'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Whether user has superuser privileges'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='Account disabled timestamp (NULL means active)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_users_email'), 'users', ['email'], unique=True, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_users_id'), 'users', ['id'], unique=False, schema='common_compass_schema')
    op.create_table('associations',
    sa.Column('source_model', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_model', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_model', 'source_id', 'target_model', 'target_id', 'link_type', name='uq_associations_source_target_type'),
    schema='common_compass_schema'
    )
    op.create_index('ix_associations_source_model_id_type', 'associations', ['source_model', 'source_id', 'link_type'], unique=False, schema='common_compass_schema')
    op.create_index('ix_associations_target_model_id_type', 'associations', ['target_model', 'target_id', 'link_type'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_associations_id'), 'associations', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_associations_link_type'), 'associations', ['link_type'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_associations_source_id'), 'associations', ['source_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_associations_source_model'), 'associations', ['source_model'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_associations_target_id'), 'associations', ['target_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_associations_target_model'), 'associations', ['target_model'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_associations_user_id'), 'associations', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('dimensions',
    sa.Column('name', sa.String(length=100), nullable=False, comment="Dimension name (e.g., 'Work', 'Health', 'Family')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of this life dimension'),
    sa.Column('color', sa.String(length=7), nullable=False, comment="Color code for this dimension (hex format, e.g., '#3B82F6')"),
    sa.Column('icon', sa.String(length=50), nullable=True, comment="Icon identifier for this dimension (e.g., 'work', 'health')"),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Whether this dimension is currently active'),
    sa.Column('display_order', sa.Integer(), nullable=True, comment='Display order for this dimension'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_dimensions_id'), 'dimensions', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_dimensions_name'), 'dimensions', ['name'], unique=True, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_dimensions_user_id'), 'dimensions', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('foods',
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Owner of the food item. NULL for common foods.'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Food name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Additional description of the food'),
    sa.Column('is_common', sa.Boolean(), nullable=False, comment='Whether this is a commonly used food item'),
    sa.Column('calories_per_100g', sa.Float(), nullable=True, comment='Calories per 100g'),
    sa.Column('protein_per_100g', sa.Float(), nullable=True, comment='Protein content per 100g (g)'),
    sa.Column('carbs_per_100g', sa.Float(), nullable=True, comment='Carbohydrate content per 100g (g)'),
    sa.Column('fat_per_100g', sa.Float(), nullable=True, comment='Fat content per 100g (g)'),
    sa.Column('fiber_per_100g', sa.Float(), nullable=True, comment='Fiber content per 100g (g)'),
    sa.Column('sugar_per_100g', sa.Float(), nullable=True, comment='Sugar content per 100g (g)'),
    sa.Column('sodium_per_100g', sa.Float(), nullable=True, comment='Sodium content per 100g (mg)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_foods_id'), 'foods', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_foods_name'), 'foods', ['name'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_foods_user_id'), 'foods', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('notes',
    sa.Column('content', sa.Text(), nullable=False, comment='The main content of the note'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_notes_id'), 'notes', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_notes_user_id'), 'notes', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('persons',
    sa.Column('name', sa.String(length=200), nullable=True, comment="Person's name (can be null for anonymous contacts)"),
    sa.Column('nicknames', sa.JSON(), nullable=True, comment='Array of nicknames/aliases for this person'),
    sa.Column('birth_date', sa.Date(), nullable=True, comment="Person's birth date"),
    sa.Column('location', sa.String(length=200), nullable=True, comment="Person's location or address"),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_persons_id'), 'persons', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_persons_location'), 'persons', ['location'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_persons_name'), 'persons', ['name'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_persons_user_id'), 'persons', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('tags',
    sa.Column('name', sa.String(length=100), nullable=False, comment="Tag name (e.g., 'family', 'important', 'work', 'personal')"),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment="Entity type this tag is designed for: 'person', 'note', 'task', 'vision', 'general'"),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description explaining the purpose of this tag'),
    sa.Column('color', sa.String(length=7), nullable=True, comment="Color code for this tag (hex format, e.g., '#3B82F6')"),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_tags_entity_type'), 'tags', ['entity_type'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_tags_id'), 'tags', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_tags_name'), 'tags', ['name'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_tags_user_id'), 'tags', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_index('ix_tags_name_entity_type', 'tags', ['name', 'entity_type'], unique=False, schema='common_compass_schema')
    op.create_table('user_preferences',
    sa.Column('key', sa.String(length=100), nullable=False, comment="Preference key (e.g., 'theme', 'language', 'notifications.email')"),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Preference value stored as JSON'),
    sa.Column('module', sa.String(length=50), nullable=False, comment="Module or category this preference belongs to (e.g., 'ui', 'notifications', 'calendar')"),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_preferences_user_key'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_user_preferences_id'), 'user_preferences', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_user_preferences_key'), 'user_preferences', ['key'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_user_preferences_module'), 'user_preferences', ['module'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('agent_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module_key', sa.String(length=64), nullable=True),
    sa.Column('dimension_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.ForeignKeyConstraint(['dimension_id'], ['common_compass_schema.dimensions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('anniversaries',
    sa.Column('person_id', sa.UUID(), nullable=False, comment='ID of the person this anniversary belongs to'),
    sa.Column('name', sa.String(length=200), nullable=False, comment="Anniversary name (e.g., 'First Met', 'Wedding Anniversary')"),
    sa.Column('date', sa.Date(), nullable=False, comment='Anniversary date'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['person_id'], ['common_compass_schema.persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_anniversaries_date'), 'anniversaries', ['date'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_anniversaries_id'), 'anniversaries', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_anniversaries_name'), 'anniversaries', ['name'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_anniversaries_person_id'), 'anniversaries', ['person_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_anniversaries_user_id'), 'anniversaries', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('daily_dimension_stats',
    sa.Column('stat_date', sa.Date(), nullable=False, comment='UTC calendar date of the statistic'),
    sa.Column('dimension_id', sa.UUID(), nullable=False, comment='Referenced dimension id'),
    sa.Column('timezone', sa.String(length=64), nullable=False, comment='Timezone identifier used for this aggregation (IANA format)'),
    sa.Column('minutes', sa.Integer(), nullable=False, comment='Total minutes for the day and dimension'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['dimension_id'], ['common_compass_schema.dimensions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'stat_date', 'dimension_id', 'timezone', name='uq_daily_dimension_stats_user_date_dim_timezone'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_daily_dimension_stats_id'), 'daily_dimension_stats', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_daily_dimension_stats_user_id'), 'daily_dimension_stats', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_index('ix_daily_dim_user_date_timezone', 'daily_dimension_stats', ['user_id', 'stat_date', 'timezone'], unique=False, schema='common_compass_schema')
    op.create_index('ix_daily_dim_user_dimension_timezone', 'daily_dimension_stats', ['user_id', 'dimension_id', 'timezone'], unique=False, schema='common_compass_schema')
    op.create_table('food_entries',
    sa.Column('date', sa.String(length=10), nullable=False, comment='Date in YYYY-MM-DD format'),
    sa.Column('consumed_at', sa.DateTime(), nullable=False, comment='Exact time when food was consumed'),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', 'other', name='mealtype', schema='common_compass_schema'), nullable=False, comment='Type of meal'),
    sa.Column('food_id', sa.UUID(), nullable=False, comment='ID of the food item consumed'),
    sa.Column('portion_size_g', sa.Float(), nullable=False, comment='Portion size in grams'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes about this food entry'),
    sa.Column('calories', sa.Float(), nullable=True, comment='Calculated calories for this portion'),
    sa.Column('protein', sa.Float(), nullable=True, comment='Calculated protein for this portion (g)'),
    sa.Column('carbs', sa.Float(), nullable=True, comment='Calculated carbohydrates for this portion (g)'),
    sa.Column('fat', sa.Float(), nullable=True, comment='Calculated fat for this portion (g)'),
    sa.Column('fiber', sa.Float(), nullable=True, comment='Calculated fiber for this portion (g)'),
    sa.Column('sugar', sa.Float(), nullable=True, comment='Calculated sugar for this portion (g)'),
    sa.Column('sodium', sa.Float(), nullable=True, comment='Calculated sodium for this portion (mg)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.ForeignKeyConstraint(['food_id'], ['common_compass_schema.foods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_food_entries_consumed_at'), 'food_entries', ['consumed_at'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_food_entries_date'), 'food_entries', ['date'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_food_entries_food_id'), 'food_entries', ['food_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_food_entries_id'), 'food_entries', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_food_entries_user_id'), 'food_entries', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('tag_associations',
    sa.Column('entity_id', sa.UUID(), nullable=False, comment='ID of the entity being tagged'),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment="Type of the entity being tagged (e.g., 'person', 'note', 'task')"),
    sa.Column('tag_id', sa.UUID(), nullable=False, comment='ID of the tag being applied'),
    sa.ForeignKeyConstraint(['tag_id'], ['common_compass_schema.tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id', 'entity_type', 'tag_id'),
    sa.UniqueConstraint('entity_id', 'entity_type', 'tag_id', name='uq_tag_associations_entity_tag'),
    schema='common_compass_schema'
    )
    op.create_index('ix_tag_associations_entity', 'tag_associations', ['entity_type', 'entity_id'], unique=False, schema='common_compass_schema')
    op.create_index('ix_tag_associations_tag', 'tag_associations', ['tag_id'], unique=False, schema='common_compass_schema')
    op.create_table('visions',
    sa.Column('name', sa.String(length=200), nullable=False, comment="Vision name (e.g., 'Complete v1.0 Prototype', 'Master Guitar')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of this vision and its significance'),
    sa.Column('status', sa.String(length=20), nullable=False, comment="Vision status: 'active', 'archived', 'fruit'"),
    sa.Column('stage', sa.Integer(), nullable=False, comment='Growth stage of the tree (0-10, used for 3D model selection)'),
    sa.Column('experience_points', sa.Integer(), nullable=False, comment='Accumulated experience points that drive stage evolution'),
    sa.Column('dimension_id', sa.UUID(), nullable=True, comment='Default life dimension for this vision (inherited by tasks and quick entries)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.ForeignKeyConstraint(['dimension_id'], ['common_compass_schema.dimensions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_visions_dimension_id'), 'visions', ['dimension_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_visions_id'), 'visions', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_visions_name'), 'visions', ['name'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_visions_status'), 'visions', ['status'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_visions_user_id'), 'visions', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('agent_messages',
    sa.Column('session_id', sa.UUID(), nullable=True, comment='Session identifier for grouping related messages'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sender', sa.String(length=10), nullable=False),
    sa.Column('is_typing', sa.Boolean(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True, comment='LLM model used'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True, comment='Input tokens'),
    sa.Column('completion_tokens', sa.Integer(), nullable=True, comment='Output tokens'),
    sa.Column('total_tokens', sa.Integer(), nullable=True, comment='Total tokens'),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True, comment='Cost in USD'),
    sa.Column('response_time_ms', sa.Integer(), nullable=True, comment='Response time in milliseconds'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.ForeignKeyConstraint(['session_id'], ['common_compass_schema.agent_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_agent_messages_id'), 'agent_messages', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_agent_messages_session_id'), 'agent_messages', ['session_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_agent_messages_user_id'), 'agent_messages', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('tasks',
    sa.Column('vision_id', sa.UUID(), nullable=False, comment='ID of the vision this task belongs to'),
    sa.Column('parent_task_id', sa.UUID(), nullable=True, comment='ID of the parent task (for hierarchical tasks)'),
    sa.Column('content', sa.String(length=500), nullable=False, comment='Task description or title'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes or details about the task'),
    sa.Column('status', sa.String(length=20), nullable=False, comment="Task status: 'todo', 'in_progress', 'done', 'cancelled', 'paused'"),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Task priority (higher numbers = higher priority)'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='Display order within the same parent/vision'),
    sa.Column('estimated_effort', sa.Integer(), nullable=True, comment='Estimated effort in minutes'),
    sa.Column('planning_cycle_type', sa.String(length=10), nullable=True, comment='Planning cycle type: year, month, week, day'),
    sa.Column('planning_cycle_days', sa.Integer(), nullable=True, comment='Cycle duration in days'),
    sa.Column('planning_cycle_start_date', sa.Date(), nullable=True, comment='Cycle start date'),
    sa.Column('actual_effort_self', sa.Integer(), nullable=False, comment='Minutes from ActualEvents directly attached to this task'),
    sa.Column('actual_effort_total', sa.Integer(), nullable=False, comment='Minutes including this task self and all descendant tasks'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['common_compass_schema.tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vision_id'], ['common_compass_schema.visions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_tasks_content'), 'tasks', ['content'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_tasks_id'), 'tasks', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_tasks_planning_cycle_start_date'), 'tasks', ['planning_cycle_start_date'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_tasks_planning_cycle_type'), 'tasks', ['planning_cycle_type'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_tasks_priority'), 'tasks', ['priority'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_tasks_status'), 'tasks', ['status'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_tasks_user_id'), 'tasks', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_tasks_vision_id'), 'tasks', ['vision_id'], unique=False, schema='common_compass_schema')
    op.create_table('actual_events',
    sa.Column('title', sa.String(length=200), nullable=False, comment='Actual activity title'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='Actual start time'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='Actual end time'),
    sa.Column('task_id', sa.UUID(), nullable=True, comment='Reference to the associated task (many ActualEvents to one Task)'),
    sa.Column('dimension_id', sa.UUID(), nullable=True, comment='Reference to life dimension this activity belongs to'),
    sa.Column('tracking_method', sa.String(length=20), nullable=True, comment='How this was tracked: manual, automatic, imported'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='Where this activity took place'),
    sa.Column('energy_level', sa.Integer(), nullable=True, comment='Energy level during activity (1-5)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Personal notes and reflections'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='Activity tags as JSON array'),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='Additional metadata as JSON'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.ForeignKeyConstraint(['dimension_id'], ['common_compass_schema.dimensions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['common_compass_schema.tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_actual_events_dimension_id'), 'actual_events', ['dimension_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_actual_events_end_time'), 'actual_events', ['end_time'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_actual_events_id'), 'actual_events', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_actual_events_start_time'), 'actual_events', ['start_time'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_actual_events_task_id'), 'actual_events', ['task_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_actual_events_title'), 'actual_events', ['title'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_actual_events_user_id'), 'actual_events', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('habits',
    sa.Column('title', sa.String(length=200), nullable=False, comment="Habit title (e.g., 'Daily Exercise', 'Read 30 minutes')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of this habit and its significance'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Start date of the habit (cannot be modified after creation)'),
    sa.Column('duration_days', sa.Integer(), nullable=False, comment='Duration in days: 7, 14, 21, 100, 365, or 1000'),
    sa.Column('status', sa.String(length=20), nullable=False, comment="Habit status: 'active', 'completed', 'paused'"),
    sa.Column('task_id', sa.UUID(), nullable=True, comment='ID of the associated task (optional)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.CheckConstraint('duration_days IN (7, 14, 21, 100, 365, 1000)', name='valid_duration_days'),
    sa.ForeignKeyConstraint(['task_id'], ['common_compass_schema.tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_habits_id'), 'habits', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_habits_start_date'), 'habits', ['start_date'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_habits_status'), 'habits', ['status'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_habits_task_id'), 'habits', ['task_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_habits_title'), 'habits', ['title'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_habits_user_id'), 'habits', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('planned_events',
    sa.Column('title', sa.String(length=200), nullable=False, comment='Event title'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='Planned start time'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='Planned end time'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='Priority level (0-5, higher is more important)'),
    sa.Column('dimension_id', sa.UUID(), nullable=True, comment='Reference to life dimension this event belongs to'),
    sa.Column('task_id', sa.UUID(), nullable=True, comment='Optional reference to task this event is planned to work on'),
    sa.Column('is_all_day', sa.Boolean(), nullable=True, comment='Whether this is an all-day event'),
    sa.Column('is_recurring', sa.Boolean(), nullable=True, comment='Whether this event recurs'),
    sa.Column('recurrence_pattern', sa.JSON(), nullable=True, comment='Recurrence pattern details'),
    sa.Column('rrule_string', sa.Text(), nullable=True, comment='RRULE string for recurring events (RFC 5545)'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Event status: planned, cancelled, completed'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='Event tags as JSON array'),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='Additional metadata as JSON'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.ForeignKeyConstraint(['dimension_id'], ['common_compass_schema.dimensions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['common_compass_schema.tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_planned_events_dimension_id'), 'planned_events', ['dimension_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_planned_events_end_time'), 'planned_events', ['end_time'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_planned_events_id'), 'planned_events', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_planned_events_is_recurring'), 'planned_events', ['is_recurring'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_planned_events_priority'), 'planned_events', ['priority'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_planned_events_start_time'), 'planned_events', ['start_time'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_planned_events_status'), 'planned_events', ['status'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_planned_events_task_id'), 'planned_events', ['task_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_planned_events_title'), 'planned_events', ['title'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_planned_events_user_id'), 'planned_events', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('habit_actions',
    sa.Column('habit_id', sa.UUID(), nullable=False, comment='ID of the habit this action belongs to'),
    sa.Column('action_date', sa.Date(), nullable=False, comment='The specific date for this action'),
    sa.Column('status', sa.String(length=20), nullable=False, comment="Action status: 'inbox', 'todo', 'doing', 'done', 'failed', 'pass'"),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes or details about this action'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.CheckConstraint("status IN ('inbox', 'todo', 'doing', 'done', 'failed', 'pass')", name='valid_action_status'),
    sa.ForeignKeyConstraint(['habit_id'], ['common_compass_schema.habits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_habit_actions_action_date'), 'habit_actions', ['action_date'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_habit_actions_habit_id'), 'habit_actions', ['habit_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_habit_actions_id'), 'habit_actions', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_habit_actions_status'), 'habit_actions', ['status'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_habit_actions_user_id'), 'habit_actions', ['user_id'], unique=False, schema='common_compass_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_common_compass_schema_habit_actions_user_id'), table_name='habit_actions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_habit_actions_status'), table_name='habit_actions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_habit_actions_id'), table_name='habit_actions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_habit_actions_habit_id'), table_name='habit_actions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_habit_actions_action_date'), table_name='habit_actions', schema='common_compass_schema')
    op.drop_table('habit_actions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_planned_events_user_id'), table_name='planned_events', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_planned_events_title'), table_name='planned_events', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_planned_events_task_id'), table_name='planned_events', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_planned_events_status'), table_name='planned_events', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_planned_events_start_time'), table_name='planned_events', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_planned_events_priority'), table_name='planned_events', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_planned_events_is_recurring'), table_name='planned_events', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_planned_events_id'), table_name='planned_events', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_planned_events_end_time'), table_name='planned_events', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_planned_events_dimension_id'), table_name='planned_events', schema='common_compass_schema')
    op.drop_table('planned_events', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_habits_user_id'), table_name='habits', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_habits_title'), table_name='habits', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_habits_task_id'), table_name='habits', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_habits_status'), table_name='habits', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_habits_start_date'), table_name='habits', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_habits_id'), table_name='habits', schema='common_compass_schema')
    op.drop_table('habits', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_actual_events_user_id'), table_name='actual_events', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_actual_events_title'), table_name='actual_events', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_actual_events_task_id'), table_name='actual_events', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_actual_events_start_time'), table_name='actual_events', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_actual_events_id'), table_name='actual_events', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_actual_events_end_time'), table_name='actual_events', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_actual_events_dimension_id'), table_name='actual_events', schema='common_compass_schema')
    op.drop_table('actual_events', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_tasks_vision_id'), table_name='tasks', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_tasks_user_id'), table_name='tasks', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_tasks_status'), table_name='tasks', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_tasks_priority'), table_name='tasks', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_tasks_planning_cycle_type'), table_name='tasks', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_tasks_planning_cycle_start_date'), table_name='tasks', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_tasks_parent_task_id'), table_name='tasks', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_tasks_id'), table_name='tasks', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_tasks_content'), table_name='tasks', schema='common_compass_schema')
    op.drop_table('tasks', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_agent_messages_user_id'), table_name='agent_messages', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_agent_messages_session_id'), table_name='agent_messages', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_agent_messages_id'), table_name='agent_messages', schema='common_compass_schema')
    op.drop_table('agent_messages', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_visions_user_id'), table_name='visions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_visions_status'), table_name='visions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_visions_name'), table_name='visions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_visions_id'), table_name='visions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_visions_dimension_id'), table_name='visions', schema='common_compass_schema')
    op.drop_table('visions', schema='common_compass_schema')
    op.drop_index('ix_tag_associations_tag', table_name='tag_associations', schema='common_compass_schema')
    op.drop_index('ix_tag_associations_entity', table_name='tag_associations', schema='common_compass_schema')
    op.drop_table('tag_associations', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_food_entries_user_id'), table_name='food_entries', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_food_entries_id'), table_name='food_entries', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_food_entries_food_id'), table_name='food_entries', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_food_entries_date'), table_name='food_entries', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_food_entries_consumed_at'), table_name='food_entries', schema='common_compass_schema')
    op.drop_table('food_entries', schema='common_compass_schema')
    op.drop_index('ix_daily_dim_user_dimension_timezone', table_name='daily_dimension_stats', schema='common_compass_schema')
    op.drop_index('ix_daily_dim_user_date_timezone', table_name='daily_dimension_stats', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_daily_dimension_stats_user_id'), table_name='daily_dimension_stats', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_daily_dimension_stats_id'), table_name='daily_dimension_stats', schema='common_compass_schema')
    op.drop_table('daily_dimension_stats', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_anniversaries_user_id'), table_name='anniversaries', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_anniversaries_person_id'), table_name='anniversaries', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_anniversaries_name'), table_name='anniversaries', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_anniversaries_id'), table_name='anniversaries', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_anniversaries_date'), table_name='anniversaries', schema='common_compass_schema')
    op.drop_table('anniversaries', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_agent_sessions_user_id'), table_name='agent_sessions', schema='common_compass_schema')
    op.drop_table('agent_sessions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_user_preferences_user_id'), table_name='user_preferences', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_user_preferences_module'), table_name='user_preferences', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_user_preferences_key'), table_name='user_preferences', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_user_preferences_id'), table_name='user_preferences', schema='common_compass_schema')
    op.drop_table('user_preferences', schema='common_compass_schema')
    op.drop_index('ix_tags_name_entity_type', table_name='tags', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_tags_user_id'), table_name='tags', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_tags_name'), table_name='tags', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_tags_id'), table_name='tags', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_tags_entity_type'), table_name='tags', schema='common_compass_schema')
    op.drop_table('tags', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_persons_user_id'), table_name='persons', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_persons_name'), table_name='persons', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_persons_location'), table_name='persons', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_persons_id'), table_name='persons', schema='common_compass_schema')
    op.drop_table('persons', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_notes_user_id'), table_name='notes', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_notes_id'), table_name='notes', schema='common_compass_schema')
    op.drop_table('notes', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_foods_user_id'), table_name='foods', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_foods_name'), table_name='foods', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_foods_id'), table_name='foods', schema='common_compass_schema')
    op.drop_table('foods', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_dimensions_user_id'), table_name='dimensions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_dimensions_name'), table_name='dimensions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_dimensions_id'), table_name='dimensions', schema='common_compass_schema')
    op.drop_table('dimensions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_associations_user_id'), table_name='associations', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_associations_target_model'), table_name='associations', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_associations_target_id'), table_name='associations', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_associations_source_model'), table_name='associations', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_associations_source_id'), table_name='associations', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_associations_link_type'), table_name='associations', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_associations_id'), table_name='associations', schema='common_compass_schema')
    op.drop_index('ix_associations_target_model_id_type', table_name='associations', schema='common_compass_schema')
    op.drop_index('ix_associations_source_model_id_type', table_name='associations', schema='common_compass_schema')
    op.drop_table('associations', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_users_id'), table_name='users', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_users_email'), table_name='users', schema='common_compass_schema')
    op.drop_table('users', schema='common_compass_schema')
    # ### end Alembic commands ###
