"""daily review run

Revision ID: 46d22bc1e2fe
Revises: 9fc0bc12ae9c
Create Date: 2025-10-03 09:37:53.301599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46d22bc1e2fe'
down_revision = '9fc0bc12ae9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_review_runs',
    sa.Column('target_date', sa.Date(), nullable=False, comment='the date of the daily review'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='the status of the daily review'),
    sa.Column('trigger_source', sa.String(length=32), nullable=False, comment='the source of the daily review'),
    sa.Column('input_box_name', sa.String(length=255), nullable=True, comment='the name of the daily review input CardBox'),
    sa.Column('output_box_name', sa.String(length=255), nullable=True, comment='the name of the daily review output CardBox'),
    sa.Column('error_message', sa.String(length=1024), nullable=True, comment='the error message of the daily review'),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='the extra information of the daily review'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_daily_review_runs_id'), 'daily_review_runs', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_daily_review_runs_user_id'), 'daily_review_runs', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_index('ix_daily_review_runs_user_date', 'daily_review_runs', ['user_id', 'target_date'], unique=False, schema='common_compass_schema', postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_review_runs_user_date', table_name='daily_review_runs', schema='common_compass_schema', postgresql_using='btree')
    op.drop_index(op.f('ix_common_compass_schema_daily_review_runs_user_id'), table_name='daily_review_runs', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_daily_review_runs_id'), table_name='daily_review_runs', schema='common_compass_schema')
    op.drop_table('daily_review_runs', schema='common_compass_schema')
    # ### end Alembic commands ###
