"""add_sage_maxims

Revision ID: 34862baa9b20
Revises: 6c6b8f4b9d42
Create Date: 2025-10-17 13:13:13.808529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34862baa9b20'
down_revision = '6c6b8f4b9d42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sage_maxims',
    sa.Column('content', sa.Text(), nullable=False, comment='Maxim content provided by the author'),
    sa.Column('language', sa.String(length=16), server_default='zh-CN', nullable=False, comment='ISO language tag for the maxim'),
    sa.Column('random_weight', sa.String(length=36), server_default='', nullable=False, comment='Random seed helper for lightweight shuffling'),
    sa.Column('like_count', sa.Integer(), server_default='0', nullable=False, comment='Number of positive reactions'),
    sa.Column('dislike_count', sa.Integer(), server_default='0', nullable=False, comment='Number of negative reactions'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_sage_maxims_id'), 'sage_maxims', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_sage_maxims_user_id'), 'sage_maxims', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('sage_maxim_reactions',
    sa.Column('maxim_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reaction_type', sa.Enum('like', 'dislike', name='sage_maxim_reaction_type',schema='common_compass_schema'), nullable=False, comment='User reaction type'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['maxim_id'], ['common_compass_schema.sage_maxims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('maxim_id', 'user_id', name='uq_sage_maxim_reaction'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_sage_maxim_reactions_id'), 'sage_maxim_reactions', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_sage_maxim_reactions_maxim_id'), 'sage_maxim_reactions', ['maxim_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_sage_maxim_reactions_user_id'), 'sage_maxim_reactions', ['user_id'], unique=False, schema='common_compass_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_common_compass_schema_sage_maxim_reactions_user_id'), table_name='sage_maxim_reactions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_sage_maxim_reactions_maxim_id'), table_name='sage_maxim_reactions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_sage_maxim_reactions_id'), table_name='sage_maxim_reactions', schema='common_compass_schema')
    op.drop_table('sage_maxim_reactions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_sage_maxims_user_id'), table_name='sage_maxims', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_sage_maxims_id'), table_name='sage_maxims', schema='common_compass_schema')
    op.drop_table('sage_maxims', schema='common_compass_schema')
    # ### end Alembic commands ###
