"""add cardbox fields

Revision ID: 9fc0bc12ae9c
Revises: 68e3e7021941
Create Date: 2025-10-02 16:18:59.405888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc0bc12ae9c'
down_revision = '68e3e7021941'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_messages', sa.Column('cardbox_card_id', sa.String(length=64), nullable=True, comment='Identifier of the synced Cardbox card'), schema='common_compass_schema')
    op.add_column('agent_sessions', sa.Column('cardbox_name', sa.String(length=255), nullable=True), schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_agent_sessions_cardbox_name'), 'agent_sessions', ['cardbox_name'], unique=False, schema='common_compass_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_common_compass_schema_agent_sessions_cardbox_name'), table_name='agent_sessions', schema='common_compass_schema')
    op.drop_column('agent_sessions', 'cardbox_name', schema='common_compass_schema')
    op.drop_column('agent_messages', 'cardbox_card_id', schema='common_compass_schema')
    # ### end Alembic commands ###
