"""add finance tables

Revision ID: 3169578ad86b
Revises: 969950a8b368
Create Date: 2025-10-14 19:17:41.476460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3169578ad86b'
down_revision = '969950a8b368'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashflow_snapshots',
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('primary_currency', sa.String(length=16), nullable=False),
    sa.Column('total_income', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_expense', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('net_cashflow', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index('ix_cashflow_snapshots_user_period', 'cashflow_snapshots', ['user_id', 'period_start', 'period_end'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_cashflow_snapshots_id'), 'cashflow_snapshots', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_cashflow_snapshots_user_id'), 'cashflow_snapshots', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('cashflow_sources',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.ForeignKeyConstraint(['parent_id'], ['common_compass_schema.cashflow_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'parent_id', 'name', name='uq_cashflow_source_parent_name'),
    schema='common_compass_schema'
    )
    op.create_index('ix_cashflow_sources_user_path', 'cashflow_sources', ['user_id', 'path'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_cashflow_sources_id'), 'cashflow_sources', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_cashflow_sources_user_id'), 'cashflow_sources', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('finance_accounts',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('nature', sa.String(length=32), nullable=True),
    sa.Column('currency_code', sa.String(length=16), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.CheckConstraint('depth >= 0', name='ck_finance_account_depth_nonnegative'),
    sa.ForeignKeyConstraint(['parent_id'], ['common_compass_schema.finance_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'parent_id', 'name', name='uq_finance_account_parent_name'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_finance_accounts_id'), 'finance_accounts', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_finance_accounts_name'), 'finance_accounts', ['name'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_finance_accounts_parent_id'), 'finance_accounts', ['parent_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_finance_accounts_path'), 'finance_accounts', ['path'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_finance_accounts_user_id'), 'finance_accounts', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_index('ix_finance_accounts_user_path', 'finance_accounts', ['user_id', 'path'], unique=True, schema='common_compass_schema')
    op.create_table('finance_snapshots',
    sa.Column('snapshot_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('primary_currency', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_via', sa.String(length=32), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exchange_rates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_finance_snapshots_id'), 'finance_snapshots', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_finance_snapshots_user_id'), 'finance_snapshots', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_index('ix_finance_snapshots_user_ts', 'finance_snapshots', ['user_id', 'snapshot_ts'], unique=False, schema='common_compass_schema')
    op.create_table('cashflow_snapshot_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency_code', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['common_compass_schema.cashflow_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['common_compass_schema.cashflow_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'source_id', name='uq_cashflow_snapshot_entry_source'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_cashflow_snapshot_entries_snapshot_id'), 'cashflow_snapshot_entries', ['snapshot_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_cashflow_snapshot_entries_source_id'), 'cashflow_snapshot_entries', ['source_id'], unique=False, schema='common_compass_schema')
    op.create_table('finance_snapshot_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('balance_original', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency_code', sa.String(length=16), nullable=False),
    sa.Column('balance_converted', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['common_compass_schema.finance_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['common_compass_schema.finance_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'account_id', name='uq_finance_snapshot_entry_account'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_finance_snapshot_entries_account_id'), 'finance_snapshot_entries', ['account_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_finance_snapshot_entries_snapshot_id'), 'finance_snapshot_entries', ['snapshot_id'], unique=False, schema='common_compass_schema')
    op.alter_column('habits', 'duration_days',
               existing_type=sa.INTEGER(),
               comment='Duration in days: 5, 7, 14, 21, 100, 365, or 1000',
               existing_comment='Duration in days: 7, 14, 21, 100, 365, or 1000',
               existing_nullable=False,
               schema='common_compass_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habits', 'duration_days',
               existing_type=sa.INTEGER(),
               comment='Duration in days: 7, 14, 21, 100, 365, or 1000',
               existing_comment='Duration in days: 5, 7, 14, 21, 100, 365, or 1000',
               existing_nullable=False,
               schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_finance_snapshot_entries_snapshot_id'), table_name='finance_snapshot_entries', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_finance_snapshot_entries_account_id'), table_name='finance_snapshot_entries', schema='common_compass_schema')
    op.drop_table('finance_snapshot_entries', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_cashflow_snapshot_entries_source_id'), table_name='cashflow_snapshot_entries', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_cashflow_snapshot_entries_snapshot_id'), table_name='cashflow_snapshot_entries', schema='common_compass_schema')
    op.drop_table('cashflow_snapshot_entries', schema='common_compass_schema')
    op.drop_index('ix_finance_snapshots_user_ts', table_name='finance_snapshots', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_finance_snapshots_user_id'), table_name='finance_snapshots', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_finance_snapshots_id'), table_name='finance_snapshots', schema='common_compass_schema')
    op.drop_table('finance_snapshots', schema='common_compass_schema')
    op.drop_index('ix_finance_accounts_user_path', table_name='finance_accounts', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_finance_accounts_user_id'), table_name='finance_accounts', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_finance_accounts_path'), table_name='finance_accounts', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_finance_accounts_parent_id'), table_name='finance_accounts', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_finance_accounts_name'), table_name='finance_accounts', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_finance_accounts_id'), table_name='finance_accounts', schema='common_compass_schema')
    op.drop_table('finance_accounts', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_cashflow_sources_user_id'), table_name='cashflow_sources', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_cashflow_sources_id'), table_name='cashflow_sources', schema='common_compass_schema')
    op.drop_index('ix_cashflow_sources_user_path', table_name='cashflow_sources', schema='common_compass_schema')
    op.drop_table('cashflow_sources', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_cashflow_snapshots_user_id'), table_name='cashflow_snapshots', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_cashflow_snapshots_id'), table_name='cashflow_snapshots', schema='common_compass_schema')
    op.drop_index('ix_cashflow_snapshots_user_period', table_name='cashflow_snapshots', schema='common_compass_schema')
    op.drop_table('cashflow_snapshots', schema='common_compass_schema')
    # ### end Alembic commands ###
