"""add user daily llm usage table

Revision ID: 019c95caa9b1
Revises: 66f91eb2388d
Create Date: 2025-11-07 15:02:47.915362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019c95caa9b1'
down_revision = '66f91eb2388d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_daily_llm_usage',
    sa.Column('usage_date', sa.Date(), nullable=False, comment='UTC natural date when LLM consumption occurred'),
    sa.Column('tokens_total', sa.Integer(), server_default='0', nullable=False, comment='Cumulative total_tokens for the day'),
    sa.Column('request_count', sa.Integer(), server_default='0', nullable=False, comment='Number of LLM requests triggered on the day'),
    sa.Column('max_tokens_snapshot', sa.Integer(), nullable=True, comment='Records max_tokens configuration at request time for traceability'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_date', name='uq_user_daily_llm_usage_user_date'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_user_daily_llm_usage_user_id'), 'user_daily_llm_usage', ['user_id'], unique=False, schema='common_compass_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_common_compass_schema_user_daily_llm_usage_user_id'), table_name='user_daily_llm_usage', schema='common_compass_schema')
    op.drop_table('user_daily_llm_usage', schema='common_compass_schema')
    # ### end Alembic commands ###
