"""add_actual_event_quick_templates

Revision ID: 52acb08a7b94
Revises: 9e051fca31d6
Create Date: 2025-10-17 17:55:21.953339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52acb08a7b94'
down_revision = '9e051fca31d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actual_event_quick_templates',
    sa.Column('title', sa.String(length=200), nullable=False, comment='Display name for the template'),
    sa.Column('title_normalized', sa.String(length=200), nullable=False, comment='Lowercase trimmed title for uniqueness enforcement'),
    sa.Column('dimension_id', sa.UUID(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('default_duration_minutes', sa.Integer(), nullable=True, comment='Optional default duration in minutes'),
    sa.Column('position', sa.Integer(), nullable=False, comment='Manual ordering position for templates'),
    sa.Column('usage_count', sa.Integer(), nullable=False, comment='How many times the template has been applied'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last usage event'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.ForeignKeyConstraint(['dimension_id'], ['common_compass_schema.dimensions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['common_compass_schema.persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'title_normalized', name='uq_actual_event_quick_templates_user_title'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_actual_event_quick_templates_dimension_id'), 'actual_event_quick_templates', ['dimension_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_actual_event_quick_templates_person_id'), 'actual_event_quick_templates', ['person_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_actual_event_quick_templates_user_id'), 'actual_event_quick_templates', ['user_id'], unique=False, schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_actual_events_id'), table_name='actual_events', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_agent_messages_id'), table_name='agent_messages', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_aggregated_dimension_stats_id'), table_name='aggregated_dimension_stats', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_anniversaries_id'), table_name='anniversaries', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_associations_id'), table_name='associations', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_cashflow_snapshots_id'), table_name='cashflow_snapshots', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_cashflow_sources_id'), table_name='cashflow_sources', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_daily_dimension_stats_id'), table_name='daily_dimension_stats', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_daily_review_runs_id'), table_name='daily_review_runs', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_dimensions_id'), table_name='dimensions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_finance_accounts_id'), table_name='finance_accounts', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_finance_snapshots_id'), table_name='finance_snapshots', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_food_entries_id'), table_name='food_entries', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_foods_id'), table_name='foods', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_habit_actions_id'), table_name='habit_actions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_habits_id'), table_name='habits', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_notes_id'), table_name='notes', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_persons_id'), table_name='persons', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_planned_events_id'), table_name='planned_events', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_sage_maxim_reactions_id'), table_name='sage_maxim_reactions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_sage_maxims_id'), table_name='sage_maxims', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_tags_id'), table_name='tags', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_tasks_id'), table_name='tasks', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_user_preferences_id'), table_name='user_preferences', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_users_id'), table_name='users', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_visions_id'), table_name='visions', schema='common_compass_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_common_compass_schema_visions_id'), 'visions', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_users_id'), 'users', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_user_preferences_id'), 'user_preferences', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_tasks_id'), 'tasks', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_tags_id'), 'tags', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_sage_maxims_id'), 'sage_maxims', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_sage_maxim_reactions_id'), 'sage_maxim_reactions', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_planned_events_id'), 'planned_events', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_persons_id'), 'persons', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_notes_id'), 'notes', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_habits_id'), 'habits', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_habit_actions_id'), 'habit_actions', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_foods_id'), 'foods', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_food_entries_id'), 'food_entries', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_finance_snapshots_id'), 'finance_snapshots', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_finance_accounts_id'), 'finance_accounts', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_dimensions_id'), 'dimensions', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_daily_review_runs_id'), 'daily_review_runs', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_daily_dimension_stats_id'), 'daily_dimension_stats', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_cashflow_sources_id'), 'cashflow_sources', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_cashflow_snapshots_id'), 'cashflow_snapshots', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_associations_id'), 'associations', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_anniversaries_id'), 'anniversaries', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_aggregated_dimension_stats_id'), 'aggregated_dimension_stats', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_agent_messages_id'), 'agent_messages', ['id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_actual_events_id'), 'actual_events', ['id'], unique=False, schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_actual_event_quick_templates_user_id'), table_name='actual_event_quick_templates', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_actual_event_quick_templates_person_id'), table_name='actual_event_quick_templates', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_actual_event_quick_templates_dimension_id'), table_name='actual_event_quick_templates', schema='common_compass_schema')
    op.drop_table('actual_event_quick_templates', schema='common_compass_schema')
    # ### end Alembic commands ###
