"""Add plan binding to exchange rates

Revision ID: de6d75d7f88a
Revises: 814f7cb4c87b
Create Date: 2025-11-17 21:26:28.436666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6d75d7f88a'
down_revision = '814f7cb4c87b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_rates', sa.Column('plan_id', sa.UUID(), nullable=True), schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_exchange_rates_plan_id'), 'exchange_rates', ['plan_id'], unique=False, schema='common_compass_schema')
    op.create_foreign_key(None, 'exchange_rates', 'trading_plans', ['plan_id'], ['id'], source_schema='common_compass_schema', referent_schema='common_compass_schema', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exchange_rates', schema='common_compass_schema', type_='foreignkey')
    op.drop_index(op.f('ix_common_compass_schema_exchange_rates_plan_id'), table_name='exchange_rates', schema='common_compass_schema')
    op.drop_column('exchange_rates', 'plan_id', schema='common_compass_schema')
    # ### end Alembic commands ###
