"""init

Revision ID: 6454e83804be
Revises: 
Create Date: 2026-02-08 02:17:36.642309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6454e83804be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address (unique)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='User display name'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hashed password using bcrypt'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Whether user has superuser privileges'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='Account disabled timestamp (NULL means active)'),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False, comment='Consecutive failed login attempts since last success'),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='Account temporarily locked until this timestamp'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the most recent successful login'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_users_email'), 'users', ['email'], unique=True, schema='common_compass_schema')
    op.create_table('a2a_agents',
    sa.Column('name', sa.String(length=120), nullable=False, comment='User-facing label for the A2A agent'),
    sa.Column('card_url', sa.String(length=1024), nullable=False, comment='Agent card URL'),
    sa.Column('auth_type', sa.String(length=32), server_default='none', nullable=False, comment='Authentication type (none/bearer)'),
    sa.Column('auth_header', sa.String(length=120), nullable=True, comment='HTTP header name for auth (e.g., Authorization)'),
    sa.Column('auth_scheme', sa.String(length=64), nullable=True, comment='Authentication scheme (e.g., Bearer)'),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False, comment='Whether this agent is enabled for invocation'),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Optional tags as JSON array'),
    sa.Column('extra_headers', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Additional headers to include when fetching card/invoking'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_url', name='uq_a2a_agents_user_card_url'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_a2a_agents_user_id'), 'a2a_agents', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('dimensions',
    sa.Column('name', sa.String(length=100), nullable=False, comment="Dimension name (e.g., 'Work', 'Health', 'Family')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of this life dimension'),
    sa.Column('color', sa.String(length=7), nullable=False, comment="Color code for this dimension (hex format, e.g., '#3B82F6')"),
    sa.Column('icon', sa.String(length=50), nullable=True, comment="Icon identifier for this dimension (e.g., 'work', 'health')"),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Whether this dimension is currently active'),
    sa.Column('display_order', sa.Integer(), nullable=True, comment='Display order for this dimension'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_common_compass_schema_dimensions_user_name'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_dimensions_user_id'), 'dimensions', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('invitations',
    sa.Column('code', sa.String(length=64), nullable=False, comment='Invitation code token'),
    sa.Column('creator_user_id', sa.UUID(), nullable=False, comment='User who generated the invitation'),
    sa.Column('target_email', sa.String(length=255), nullable=False, comment='Email address the invitation is bound to (lowercase)'),
    sa.Column('status', sa.Enum('PENDING', 'REGISTERED', 'REVOKED', 'EXPIRED', name='invitation_status', schema='common_compass_schema'), nullable=False, comment='Current invitation status'),
    sa.Column('target_user_id', sa.UUID(), nullable=True, comment='User who registered with this invitation'),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the invite was used for registration'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the invite was revoked'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Optional expiration timestamp'),
    sa.Column('memo', sa.Text(), nullable=True, comment='Operational notes about this invitation'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.ForeignKeyConstraint(['creator_user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['common_compass_schema.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('creator_user_id', 'target_email', name='uq_invitations_creator_email'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_invitations_creator_user_id'), 'invitations', ['creator_user_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_invitations_target_email'), 'invitations', ['target_email'], unique=False, schema='common_compass_schema')
    op.create_table('user_activity',
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Associated user if available'),
    sa.Column('event_type', sa.String(length=64), nullable=False, comment='Classification of the recorded activity'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Outcome descriptor (e.g. success/failed/blocked)'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Flexible metadata payload for the event'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_user_activity_event_type'), 'user_activity', ['event_type'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_user_activity_user_id'), 'user_activity', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('user_preferences',
    sa.Column('key', sa.String(length=100), nullable=False, comment="Preference key (e.g., 'theme', 'language', 'notifications.email')"),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Preference value stored as JSON'),
    sa.Column('module', sa.String(length=50), nullable=False, comment="Module or category this preference belongs to (e.g., 'ui', 'notifications', 'calendar')"),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_preferences_user_key'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_user_preferences_key'), 'user_preferences', ['key'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_user_preferences_module'), 'user_preferences', ['module'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('a2a_agent_credentials',
    sa.Column('agent_id', sa.UUID(), nullable=False, comment='Related A2A agent id'),
    sa.Column('encrypted_token', sa.Text(), nullable=False, comment='Encrypted bearer token (Fernet)'),
    sa.Column('token_last4', sa.String(length=12), nullable=True, comment='Last four characters of the token for display'),
    sa.Column('encryption_version', sa.Integer(), server_default='1', nullable=False, comment='Secret encryption version'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.ForeignKeyConstraint(['agent_id'], ['common_compass_schema.a2a_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'agent_id', name='uq_a2a_agent_credentials_user_agent'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_a2a_agent_credentials_agent_id'), 'a2a_agent_credentials', ['agent_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_a2a_agent_credentials_user_id'), 'a2a_agent_credentials', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('agent_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module_key', sa.String(length=64), nullable=True),
    sa.Column('dimension_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('cardbox_name', sa.String(length=255), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('session_type', sa.String(length=32), server_default='chat', nullable=False, comment='Session classification: chat/system/scheduled'),
    sa.Column('prompt_tokens_total', sa.Integer(), nullable=False, comment='Accumulated prompt tokens for the session'),
    sa.Column('completion_tokens_total', sa.Integer(), nullable=False, comment='Accumulated completion tokens for the session'),
    sa.Column('total_tokens_total', sa.Integer(), nullable=False, comment='Accumulated total tokens for the session'),
    sa.Column('cost_usd_total', sa.Numeric(precision=10, scale=6), nullable=False, comment='Accumulated USD cost for the session'),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.ForeignKeyConstraint(['dimension_id'], ['common_compass_schema.dimensions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_agent_sessions_cardbox_name'), 'agent_sessions', ['cardbox_name'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('ws_tickets',
    sa.Column('agent_id', sa.UUID(), nullable=False, comment='A2A agent bound to the ticket'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='HMAC-SHA256 hash of the WS ticket'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Ticket expiration timestamp'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the ticket was consumed'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.ForeignKeyConstraint(['agent_id'], ['common_compass_schema.a2a_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_ws_tickets_agent_id'), 'ws_tickets', ['agent_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_ws_tickets_user_id'), 'ws_tickets', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_index('ix_ws_tickets_expires_at', 'ws_tickets', ['expires_at'], unique=False, schema='common_compass_schema')
    op.create_table('a2a_schedule_tasks',
    sa.Column('name', sa.String(length=120), nullable=False, comment='User-facing task name'),
    sa.Column('agent_id', sa.UUID(), nullable=False, comment='Target A2A agent identifier'),
    sa.Column('session_id', sa.UUID(), nullable=True, comment='Scheduled session used to store recurring conversation messages'),
    sa.Column('prompt', sa.Text(), nullable=False, comment='Prompt sent to the target agent on each run'),
    sa.Column('cycle_type', sa.String(length=16), nullable=False, comment='Cycle type: daily/weekly/monthly'),
    sa.Column('time_point', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Cycle-specific trigger point definition'),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False, comment='Whether the schedule is active'),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True, comment='Next planned trigger time in UTC'),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True, comment='Most recent execution completion time in UTC'),
    sa.Column('last_run_status', sa.String(length=32), server_default='idle', nullable=False, comment='Status of the most recent execution'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL means not deleted)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.ForeignKeyConstraint(['agent_id'], ['common_compass_schema.a2a_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['common_compass_schema.agent_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index('ix_a2a_schedule_tasks_due', 'a2a_schedule_tasks', ['user_id', 'enabled', 'next_run_at'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_a2a_schedule_tasks_agent_id'), 'a2a_schedule_tasks', ['agent_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_a2a_schedule_tasks_next_run_at'), 'a2a_schedule_tasks', ['next_run_at'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_a2a_schedule_tasks_session_id'), 'a2a_schedule_tasks', ['session_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_a2a_schedule_tasks_user_id'), 'a2a_schedule_tasks', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('agent_messages',
    sa.Column('session_id', sa.UUID(), nullable=True, comment='Session identifier for grouping related messages'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sender', sa.String(length=16), nullable=False, comment='Source of the message: user/agent/system/automation'),
    sa.Column('message_type', sa.String(length=32), server_default='chat', nullable=False, comment='Message classification (chat/tool/system/etc.)'),
    sa.Column('severity', sa.String(length=16), server_default='info', nullable=False, comment='Notification severity indicator for system messages'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured metadata for the message (tool info, etc.)'),
    sa.Column('is_typing', sa.Boolean(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True, comment='LLM model used'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True, comment='Input tokens'),
    sa.Column('completion_tokens', sa.Integer(), nullable=True, comment='Output tokens'),
    sa.Column('total_tokens', sa.Integer(), nullable=True, comment='Total tokens'),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True, comment='Cost in USD'),
    sa.Column('response_time_ms', sa.Integer(), nullable=True, comment='Response time in milliseconds'),
    sa.Column('cardbox_card_id', sa.String(length=64), nullable=True, comment='Identifier of the synced Cardbox card'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.ForeignKeyConstraint(['session_id'], ['common_compass_schema.agent_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index(op.f('ix_common_compass_schema_agent_messages_session_id'), 'agent_messages', ['session_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_agent_messages_user_id'), 'agent_messages', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_table('a2a_schedule_executions',
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Owning schedule task identifier'),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False, comment='Planned trigger time for this execution'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='Execution start time'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='Execution completion time'),
    sa.Column('status', sa.String(length=32), server_default='running', nullable=False, comment='Execution status'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Failure reason if execution did not succeed'),
    sa.Column('response_content', sa.Text(), nullable=True, comment='Persisted response content returned by the target agent'),
    sa.Column('session_id', sa.UUID(), nullable=True, comment='Associated scheduled session'),
    sa.Column('user_message_id', sa.UUID(), nullable=True, comment='Generated user-side message ID'),
    sa.Column('agent_message_id', sa.UUID(), nullable=True, comment='Generated agent-side message ID'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Data owner (UUID)'),
    sa.ForeignKeyConstraint(['agent_message_id'], ['common_compass_schema.agent_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['common_compass_schema.agent_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['common_compass_schema.a2a_schedule_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['common_compass_schema.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_message_id'], ['common_compass_schema.agent_messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='common_compass_schema'
    )
    op.create_index('ix_a2a_schedule_executions_task_created', 'a2a_schedule_executions', ['task_id', 'created_at'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_a2a_schedule_executions_agent_message_id'), 'a2a_schedule_executions', ['agent_message_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_a2a_schedule_executions_session_id'), 'a2a_schedule_executions', ['session_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_a2a_schedule_executions_task_id'), 'a2a_schedule_executions', ['task_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_a2a_schedule_executions_user_id'), 'a2a_schedule_executions', ['user_id'], unique=False, schema='common_compass_schema')
    op.create_index(op.f('ix_common_compass_schema_a2a_schedule_executions_user_message_id'), 'a2a_schedule_executions', ['user_message_id'], unique=False, schema='common_compass_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_common_compass_schema_a2a_schedule_executions_user_message_id'), table_name='a2a_schedule_executions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_a2a_schedule_executions_user_id'), table_name='a2a_schedule_executions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_a2a_schedule_executions_task_id'), table_name='a2a_schedule_executions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_a2a_schedule_executions_session_id'), table_name='a2a_schedule_executions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_a2a_schedule_executions_agent_message_id'), table_name='a2a_schedule_executions', schema='common_compass_schema')
    op.drop_index('ix_a2a_schedule_executions_task_created', table_name='a2a_schedule_executions', schema='common_compass_schema')
    op.drop_table('a2a_schedule_executions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_agent_messages_user_id'), table_name='agent_messages', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_agent_messages_session_id'), table_name='agent_messages', schema='common_compass_schema')
    op.drop_table('agent_messages', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_a2a_schedule_tasks_user_id'), table_name='a2a_schedule_tasks', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_a2a_schedule_tasks_session_id'), table_name='a2a_schedule_tasks', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_a2a_schedule_tasks_next_run_at'), table_name='a2a_schedule_tasks', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_a2a_schedule_tasks_agent_id'), table_name='a2a_schedule_tasks', schema='common_compass_schema')
    op.drop_index('ix_a2a_schedule_tasks_due', table_name='a2a_schedule_tasks', schema='common_compass_schema')
    op.drop_table('a2a_schedule_tasks', schema='common_compass_schema')
    op.drop_index('ix_ws_tickets_expires_at', table_name='ws_tickets', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_ws_tickets_user_id'), table_name='ws_tickets', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_ws_tickets_agent_id'), table_name='ws_tickets', schema='common_compass_schema')
    op.drop_table('ws_tickets', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_agent_sessions_user_id'), table_name='agent_sessions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_agent_sessions_cardbox_name'), table_name='agent_sessions', schema='common_compass_schema')
    op.drop_table('agent_sessions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_a2a_agent_credentials_user_id'), table_name='a2a_agent_credentials', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_a2a_agent_credentials_agent_id'), table_name='a2a_agent_credentials', schema='common_compass_schema')
    op.drop_table('a2a_agent_credentials', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_user_preferences_user_id'), table_name='user_preferences', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_user_preferences_module'), table_name='user_preferences', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_user_preferences_key'), table_name='user_preferences', schema='common_compass_schema')
    op.drop_table('user_preferences', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_user_activity_user_id'), table_name='user_activity', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_user_activity_event_type'), table_name='user_activity', schema='common_compass_schema')
    op.drop_table('user_activity', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_invitations_target_email'), table_name='invitations', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_invitations_creator_user_id'), table_name='invitations', schema='common_compass_schema')
    op.drop_table('invitations', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_dimensions_user_id'), table_name='dimensions', schema='common_compass_schema')
    op.drop_table('dimensions', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_a2a_agents_user_id'), table_name='a2a_agents', schema='common_compass_schema')
    op.drop_table('a2a_agents', schema='common_compass_schema')
    op.drop_index(op.f('ix_common_compass_schema_users_email'), table_name='users', schema='common_compass_schema')
    op.drop_table('users', schema='common_compass_schema')
    # ### end Alembic commands ###
