"""Canonical A2A extension contract constants.

The Hub now prefers the upstream ``urn:a2a:*`` / ``urn:opencode-a2a:*`` URIs,
but still recognizes the older in-repo URIs during the transition window.
"""

from __future__ import annotations

SHARED_SESSION_BINDING_URI = "urn:a2a:session-binding/v1"
LEGACY_SHARED_SESSION_BINDING_URI = "urn:shared-a2a:session-binding:v1"
SUPPORTED_SESSION_BINDING_URIS = (
    SHARED_SESSION_BINDING_URI,
    LEGACY_SHARED_SESSION_BINDING_URI,
)

SHARED_SESSION_QUERY_URI = "urn:opencode-a2a:session-query/v1"
LEGACY_SHARED_SESSION_QUERY_URI = "urn:shared-a2a:session-query:v1"
SUPPORTED_SESSION_QUERY_URIS = (
    SHARED_SESSION_QUERY_URI,
    LEGACY_SHARED_SESSION_QUERY_URI,
)

PROVIDER_DISCOVERY_URI = "urn:opencode-a2a:provider-discovery/v1"

SHARED_INTERRUPT_CALLBACK_URI = "urn:a2a:interactive-interrupt/v1"
LEGACY_SHARED_INTERRUPT_CALLBACK_URI = "urn:shared-a2a:interrupt-callback:v1"
SUPPORTED_INTERRUPT_CALLBACK_URIS = (
    SHARED_INTERRUPT_CALLBACK_URI,
    LEGACY_SHARED_INTERRUPT_CALLBACK_URI,
)

SHARED_METADATA_KEY = "shared"
SHARED_SESSION_KEY = "session"
SHARED_STREAM_KEY = "stream"
SHARED_INTERRUPT_KEY = "interrupt"
SHARED_USAGE_KEY = "usage"

SHARED_SESSION_METADATA_FIELD = "metadata.shared.session"
SHARED_SESSION_ID_FIELD = "metadata.shared.session.id"
SHARED_STREAM_METADATA_FIELD = "metadata.shared.stream"
SHARED_INTERRUPT_METADATA_FIELD = "metadata.shared.interrupt"
SHARED_USAGE_METADATA_FIELD = "metadata.shared.usage"

CANONICAL_PROVIDER_KEY = "provider"
CANONICAL_EXTERNAL_SESSION_ID_KEY = "externalSessionId"
CANONICAL_INTERRUPT_KEY = "interrupt"

__all__ = [
    "CANONICAL_EXTERNAL_SESSION_ID_KEY",
    "CANONICAL_INTERRUPT_KEY",
    "CANONICAL_PROVIDER_KEY",
    "LEGACY_SHARED_INTERRUPT_CALLBACK_URI",
    "LEGACY_SHARED_SESSION_BINDING_URI",
    "LEGACY_SHARED_SESSION_QUERY_URI",
    "PROVIDER_DISCOVERY_URI",
    "SHARED_INTERRUPT_KEY",
    "SHARED_INTERRUPT_CALLBACK_URI",
    "SHARED_INTERRUPT_METADATA_FIELD",
    "SHARED_METADATA_KEY",
    "SHARED_SESSION_ID_FIELD",
    "SHARED_SESSION_KEY",
    "SHARED_SESSION_BINDING_URI",
    "SHARED_SESSION_METADATA_FIELD",
    "SHARED_SESSION_QUERY_URI",
    "SHARED_STREAM_KEY",
    "SHARED_STREAM_METADATA_FIELD",
    "SHARED_USAGE_KEY",
    "SHARED_USAGE_METADATA_FIELD",
    "SUPPORTED_INTERRUPT_CALLBACK_URIS",
    "SUPPORTED_SESSION_BINDING_URIS",
    "SUPPORTED_SESSION_QUERY_URIS",
]
